Install Legislation Explorer with Ansible
openfisca/legislation-explorer pull request #231
Opened 2021-10-11 08:15 UTC by cbenz

This PR makes the Legislation Explorer installable via Ansible.

Inspired from https://github.com/openfisca/openfisca-ops/pull/95

Fixes #233.

2021-10-11 09:55 UTC, MattiSG reviewed
Waiting for this PR to not be a draft anymore to Approve or Request changes 🙂

2021-10-11 09:55 UTC, MattiSG commented on ops/Vagrantfile
> +port = ENV["HOST_PORT"] || 8000
When using the command, I find it more meaningful to do `PORT=8080 vagrant up` than `HOST_PORT=8080 vagrant up`.
```suggestion
port = ENV["PORT"] || 8000
```

2021-10-11 09:55 UTC, MattiSG commented on ops/Vagrantfile
> +    # Building Legislation Explorer takes more than 1024Mb of memory (the default value).
```suggestion
    # Building Legislation Explorer takes more than the default 1024MB of memory.
```

2021-10-11 09:55 UTC, MattiSG commented on ops/ansible/roles/legislation_explorer/tasks/main.yml
> +    # Discard any local modifications otherwise the task will fail.
```suggestion
    # Discard any local changes otherwise the task will fail.
```

2021-10-11 09:55 UTC, MattiSG commented on ops/ansible/roles/legislation_explorer/tasks/main.yml
> +- name: Setup the systemd service
```suggestion
- name: Set up the systemd service
```

2021-10-11 09:55 UTC, MattiSG commented on ops/ansible/roles/legislation_explorer/tasks/main.yml
> +- name: Setup SSL
```suggestion
- name: Set SSL up
```

2021-10-11 09:55 UTC, MattiSG commented on ops/ansible/roles/legislation_explorer/defaults/main.yml
> +legislation_explorer_api_url: https://fr.openfisca.org/api/latest
In order to support internationalisation, I would prefer that default values are generic (potentially with `.example` TLD domain names), and that a specific inventory is provided for France 🙂

2021-10-14 16:13 UTC, MattiSG requested changes
If I run this code following instructions, I get a failure on the step `TASK [legislation_explorer : Check that Legislation Explorer is actually started] ***`, with the message `Request failed: <urlopen error [Errno 99] Cannot assign requested address>'`.

I tried changing `legislation_explorer_host` to `localhost`, to no avail.

2021-10-14 16:13 UTC, MattiSG commented on ops/docs/Serve-local-instance.md
> +Thanks to Vagrant port forwarding, the port 80 inside the virtual machine is forwarded to another port on your development machine. You can thus access the Legislation Explorer on your local machine
Fake news! If I change `PORT` without changing `legislation_explorer_http_port`, I get a failure :wink:

2021-10-14 16:13 UTC, MattiSG commented on ops/ansible/roles/legislation_explorer/defaults/main.yml
> +legislation_explorer_http_port: 8000
Could we set the default to something that would not collide with the default API port? 🙂 
```suggestion
legislation_explorer_http_port: 8001
```

2021-10-14 16:13 UTC, MattiSG commented on ops/ansible/roles/legislation_explorer/defaults/main.yml
> +legislation_explorer_api_url: http://openfisca-api.example
Let's use the default value of the local API.
```suggestion
legislation_explorer_api_url: http://localhost:8000
```

2021-10-20 10:10 UTC, cbenz commented on ops/docs/Serve-local-instance.md
> +Thanks to Vagrant port forwarding, the port 80 inside the virtual machine is forwarded to another port on your development machine. You can thus access the Legislation Explorer on your local machine
Good point! Fixed by updating the `Vagrantfile`.

2021-10-21 00:02 UTC, MattiSG requested changes
I get the following error when executing the playbook:

```
FAILED - RETRYING: Check that Legislation Explorer is actually started (1 retries left).
fatal: [legislation_explorer]: FAILED! => changed=false 
  attempts: 5
  content: ''
  elapsed: 0
  msg: 'Status code was -1 and not [200]: Request failed: <urlopen error [Errno 99] Cannot assign requested address>'
  redirected: false
  status: -1
  url: http://localhost:8001
```

- - - -

Could we please apply here all the changes applied in https://github.com/openfisca/openfisca-ops/pull/95/files/4d06dfa90392a4dee17c21aec5eed37825d61054..51e93fc337dc36cf8c8735d1837ffbacc89e7e5a? 🙂

2021-10-22 21:41 UTC, cbenz commented
Are you executing the playbook with `vagrant up`? If so, did you run the VM for the API first?

If I don't start the VM for the API, I get an error that is slightly different:

```
FAILED - RETRYING: Check that Legislation Explorer is actually started (1 retries left).
fatal: [legislation_explorer]: FAILED! => changed=false 
  attempts: 5
  content: ''
  elapsed: 0
  msg: 'Status code was -1 and not [200]: Request failed: <urlopen error [Errno 111] Connection refused>'
  redirected: false
  status: -1
  url: http://localhost:8001
```

But if I do start the VM of the API, I get no error.

I'm going to update the docs to explain that requirement.

Otherwise, if your error exists while the VM of the API runs, could you please help finding the error by doing...

```
vagrant ssh
# then in the VM
sudo journalctl -u legislation-explorer.service -e
```

...and spot any error in the logs?

2021-10-26 12:56 UTC, MattiSG requested changes
I still get this error when I try to execute the playbook, no matter which ports I choose:
```
fatal: [legislation_explorer]: FAILED! => changed=false 
  attempts: 5
  content: ''
  elapsed: 0
  msg: 'Status code was -1 and not [200]: Request failed: <urlopen error [Errno 99] Cannot assign requested address>'
  redirected: false
  status: -1
  url: http://localhost:8081
```

I tried with `API_PORT=8080 PORT=8081 vagrant up --provider=docker`, with obviously the API available on the host machine at `http://localhost:8080`. `http://localhost:8081` does show the default nginx page, but does not serve the legislation explorer.

I even tried editing the values manually:

```diff
 api_port = ENV["API_PORT"] || 8000
-guest_port = 8001
+guest_port = 8081
 host_port = ENV["PORT"] || 8001
```
```diff
-api_url: http://localhost:8000
+api_url: http://localhost:8080
 base_path: /
```

…to no avail.

Can we have a video discussion maybe? 🙂

2021-10-26 12:56 UTC, MattiSG commented on ops/ansible/roles/legislation_explorer/defaults/main.yml
> +port: 8001
You are right, this varname triggers a `[WARNING]: Found variable using reserved name: port`, this should be changed back, sorry 😕

2021-10-26 12:56 UTC, MattiSG commented on src/server/render.jsx
> +function trimEndSlash(value) {
Unless I am mistaken, this regexp will actually remove _all_ trailing slashes, not only the last one.
```suggestion
function trimTrailingSlashes(value) {
```

2021-10-26 12:56 UTC, MattiSG commented on ops/Vagrantfile
> +        "api_url" => "http://#{host_ip_from_guest}:#{api_port}",
Could we make this editable with an environment variable too? 🙂 This would also enable removing the comment below.

2021-10-27 10:02 UTC, cbenz commented on ops/Vagrantfile
> +        "api_url" => "http://#{host_ip_from_guest}:#{api_port}",
Are you taking about `api_port` or the whole `api_url`?

Did you see `API_PORT` at the first line of the file?

2021-10-27 20:23 UTC, MattiSG commented on ops/Vagrantfile
> +        "api_url" => "http://#{host_ip_from_guest}:#{api_port}",
I'm talking about `api_url`. My current only way to adjust when running on Vagrant is the port (or editing the Vagrantfile).

2021-10-28 22:47 UTC, cbenz commented on ops/Vagrantfile
> +        "api_url" => "http://#{host_ip_from_guest}:#{api_port}",
Following out video call, I'm removing the private network stuff. The API URL is read from the `API_URL` environment variable, with a default value for the demo API.

2021-10-29 01:44 UTC, MattiSG requested changes
Almost there!

2021-10-29 01:44 UTC, MattiSG commented on src/server/index.js
> -    console.log('Top-level error:', error)
Removing these lines impacts too strongly the current error management system and has too many chances of introducing side-effects: any error after the introduced `catch` will now disappear.

What about adding the `throw` in that global `catch` for the initial setup? 🙂

2021-10-29 08:55 UTC, cbenz commented on src/server/index.js
> -    console.log('Top-level error:', error)
> I don't think that removing those last error handlers will not hide: on old Node.js versions, they will be displayed as an `UnhandledPromiseRejectionWarning` exception, but in recent Node.js versions they will appear as normal exceptions. I tested that yesterday. 

I reverted the commit that changes that error management system.

I'm not sure I understood your last sentence: could you please do a suggestion?

As the goal is to raise an error if the initial data fails to load, I can think about a solution that does not change the last catches.

2021-10-29 11:37 UTC, MattiSG commented on ops/ansible/roles/legislation_explorer/tasks/main.yml
> +          - npm
These versions should be pinned!

2021-10-29 11:47 UTC, MattiSG commented on src/server/index.js
> -    console.log('Top-level error:', error)
See 5206b5731a91f7fbc725973ef5439259b33bdacd

2021-10-29 13:16 UTC, cbenz commented on ops/ansible/roles/legislation_explorer/tasks/main.yml
> +          - npm
https://github.com/openfisca/legislation-explorer/pull/231/commits/0d21fd2aa5382796f6946f75b0b944fcc087a322

2021-10-29 13:47 UTC, MattiSG requested changes
- [x] I again have assets that don't load properly because they are loaded as `http://style.css/`.
- [ ] CI fails because the server cannot be reached.
- [x] CI does not fail at setup while it should.

The [origin of the problem](https://app.circleci.com/pipelines/github/openfisca/legislation-explorer/51/workflows/a2f995b4-ae25-4fc8-a1d0-79a7cdc98ec2/jobs/953/parallel-runs/1/steps/1-110) for steps 2 and 3 is`Could not fetch 'https://api.demo.openfisca.org/latest/entities'`.

2021-10-29 13:59 UTC, cbenz commented
> I again have assets that don't load properly because they are loaded as http://style.css/.

Did you use `"branch_name" => "install-with-ansible",` in the `Vagrantfile`? I tried with that setting and it works. Sorry for that gotcha.

About CircleCI, I'm going to try to solve this.

2021-10-29 14:05 UTC, cbenz commented
> CI does not fail at setup while it should.

Yes, that's because of the [`.catch`](https://github.com/openfisca/legislation-explorer/blob/install-with-ansible/src/server/index.js#L72) that swallows the exception. I propose to remove it since the exception will be caught by the last `.catch` (the one in which you `throw error`).

2021-10-29 14:10 UTC, MattiSG commented
> Did you use `"branch_name" => "install-with-ansible",` in the `Vagrantfile`?

Oh no, that's what I forgot again, I'm sorry 😞
Let me try with that.

2021-10-29 14:15 UTC, MattiSG commented
Works now! 👍 Sorry that I forgot this…

> Maybe rename `branch_name` to `branch`? 🙂

2021-10-29 14:15 UTC, cbenz commented
Node.js version impacts the exit code:

<details>

<summary>with Node.js 10</summary>

```
$ nvm use 10.19.0
Now using node v10.19.0 (npm v6.13.4)

$ npm start      
> legislation-explorer@1.0.0 start /home/cbenz/Dev/openfisca/legislation-explorer
> NODE_ENV=production node --require dotenv/config index.js

Fetching initial data from Web API...
(node:589845) UnhandledPromiseRejectionWarning: Error: Could not fetch 'https://api.foo.openfisca.org/latest/entities'.
    at /home/cbenz/Dev/openfisca/legislation-explorer/src/webservices.js:8:26
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:589845) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:589845) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

$ echo $?
0
```

</details>

<details>

<summary>with Node.js 16</summary>

```
$ nvm use --lts   
Now using node v16.13.0 (npm v8.1.0)

$ npm start    
> legislation-explorer@1.0.0 start
> NODE_ENV=production node --require dotenv/config index.js

Fetching initial data from Web API...
/home/cbenz/Dev/openfisca/legislation-explorer/src/webservices.js:16
              throw new Error('Could not fetch \'' + url + '\'.');
                    ^

Error: Could not fetch 'https://api.foo.openfisca.org/latest/entities'.
    at /home/cbenz/Dev/openfisca/legislation-explorer/src/webservices.js:8:26
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

$ echo $?
1
```

</details>

2021-10-29 14:17 UTC, MattiSG commented
Yes indeed, the behaviour changed, that is why I mentioned we have to pin the version number 🙂
The version in CI is 8, you can change it by changing `image: circleci/node:8-jessie-browsers`, but if we change the production version we have to then make sure everything works with it…

2021-10-29 14:17 UTC, MattiSG commented
Feel free to just use `process.exit(1)` in the last `catch` (the one that mentioned a “top-level error”).

2021-10-29 14:19 UTC, MattiSG commented
(if you go this way, please try first `process.exitCode = 1`, as we don't know what other asynchronous tasks might be living)

2021-10-29 14:27 UTC, cbenz commented
Node.js versions used:

- old server: v6.14.4
- new server: v10.19.0
- Circle CI: 8 (I couldn't find the exact version reading https://circleci.com/docs/2.0/circleci-images/ quickly)

A `.nvmrc` file could be a source of truth, containing 6.14.4 for now as it is the version used currently by the production, and both Ansible playbook and Circle CI should use nvm.

Adapting the Ansible playbook to nvm should be OK.

> I do not know CircleCI very well, do you know how to setup nvm on CircleCI quickly?

2021-10-29 14:38 UTC, cbenz commented
Now the CI [fails](https://app.circleci.com/pipelines/github/openfisca/legislation-explorer/55/workflows/aa0dad9d-9c6f-4ed2-909a-2308ff299ca7/jobs/957) properly when the "Run app" step fails with a non-null exit code.

But I do not understand why the app fails to fetch https://api.demo.openfisca.org/latest/variables while it works locally :thinking: 

Would you know about CircleCI specificities about that issue?

2021-10-29 14:52 UTC, MattiSG commented
> Would you know about CircleCI specificities about that issue?

No.
I confirm I can reach the given URL from my machine.
I tried to [investigate with SSH](https://app.circleci.com/pipelines/github/openfisca/legislation-explorer/55/workflows/aa0dad9d-9c6f-4ed2-909a-2308ff299ca7/jobs/958):

```
$ curl https://api.demo.openfisca.org/latest/variables

curl: (60) SSL certificate problem: certificate has expired
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.

$  curl --insecure https://api.demo.openfisca.org/latest/variables
{"total_benefits":{"de…}}
```

Date on CI: `Fri Oct 29 14:53:13 UTC 2021`.

2021-10-29 14:54 UTC, MattiSG commented
Double-checking with https://www.digicert.com/:

> The certificate expires January 25, 2022 (88 days from today)

2021-10-29 14:57 UTC, MattiSG commented
Confirmed with `node` on CI:

```
$ fetch('https://api.demo.openfisca.org/latest/variables').then(console.log.bind(console), console.log.bind(console))

Promise {
  <pending>,
  domain: 
   Domain {
     domain: null,
     _events: { error: [Function: debugDomainError] },
     _eventsCount: 1,
     _maxListeners: undefined,
     members: [ [Object] ] } }
> { FetchError: request to https://api.demo.openfisca.org/latest/variables failed, reason: certificate has expired
    at ClientRequest.<anonymous> (/home/circleci/project/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:401:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
  name: 'FetchError',
  message: 'request to https://api.demo.openfisca.org/latest/variables failed, reason: certificate has expired',
  type: 'system',
  errno: 'CERT_HAS_EXPIRED',
  code: 'CERT_HAS_EXPIRED' }
```

2021-10-29 15:53 UTC, MattiSG commented
Solved with video call: Let's Encrypt cross-signed X3 certificate has been revoked, and the specified image (Debian Jessie) was too old to have up-to-date CA certificates. This was solved by letting CircleCI decide of the base image to use a more recent Debian distribution.

The Node CI version was also updated to reflect new production constraints (v10).

2021-10-29 16:04 UTC, MattiSG approved these changes
🎉

2021-10-29 16:06 UTC, merged